//Salvador Depons(303738) y Valentina Velazquez(305278)

package Interfaz;
import Dominio.*;
import javax.swing.JOptionPane;

// Clase de la ventana Alta Postulante
public class AltaPostulante extends javax.swing.JFrame {
    private Sistema modelo;
    
    // Constructor vacio
    public AltaPostulante() {
        initComponents();
    }
    
    // Constructor 
    public AltaPostulante(Sistema unSistema) {
        modelo = unSistema;
        initComponents();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoFormatoPostulante = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNombrePostulante = new javax.swing.JLabel();
        lblDireccionPostulante = new javax.swing.JLabel();
        lblCedulaPostulante = new javax.swing.JLabel();
        lblTelefonoPostulante = new javax.swing.JLabel();
        lblLinkedinPostulante = new javax.swing.JLabel();
        lblMailPostulante = new javax.swing.JLabel();
        lblFormato = new javax.swing.JLabel();
        txtCedulaPostulante = new javax.swing.JTextField();
        txtNombrePostulante = new javax.swing.JTextField();
        txtMailPostulante = new javax.swing.JTextField();
        txtLinkedinPostulante = new javax.swing.JTextField();
        txtTelefonoPostulante = new javax.swing.JTextField();
        txtDireccionPostulante = new javax.swing.JTextField();
        btnRemotoPostulante = new javax.swing.JRadioButton();
        btnMixtoPostulante = new javax.swing.JRadioButton();
        btnPresencialPostulante = new javax.swing.JRadioButton();
        btnSiguientePostulante = new javax.swing.JButton();
        btnCancelarPostulante = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alta de postulante");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Alta Postulante");

        lblNombrePostulante.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNombrePostulante.setText("Nombre: ");

        lblDireccionPostulante.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDireccionPostulante.setText("Dirección:");

        lblCedulaPostulante.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCedulaPostulante.setText("Cédula:");

        lblTelefonoPostulante.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTelefonoPostulante.setText("Teléfono: ");

        lblLinkedinPostulante.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLinkedinPostulante.setText("Linkedin:");

        lblMailPostulante.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMailPostulante.setText("Mail:");

        lblFormato.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblFormato.setText("Formato:");

        txtCedulaPostulante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaPostulanteActionPerformed(evt);
            }
        });

        txtNombrePostulante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombrePostulanteActionPerformed(evt);
            }
        });

        txtMailPostulante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMailPostulanteActionPerformed(evt);
            }
        });

        txtLinkedinPostulante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLinkedinPostulanteActionPerformed(evt);
            }
        });

        txtTelefonoPostulante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoPostulanteActionPerformed(evt);
            }
        });

        txtDireccionPostulante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionPostulanteActionPerformed(evt);
            }
        });

        GrupoFormatoPostulante.add(btnRemotoPostulante);
        btnRemotoPostulante.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnRemotoPostulante.setSelected(true);
        btnRemotoPostulante.setText("Remoto");
        btnRemotoPostulante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemotoPostulanteActionPerformed(evt);
            }
        });

        GrupoFormatoPostulante.add(btnMixtoPostulante);
        btnMixtoPostulante.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnMixtoPostulante.setText("Mixto");
        btnMixtoPostulante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMixtoPostulanteActionPerformed(evt);
            }
        });

        GrupoFormatoPostulante.add(btnPresencialPostulante);
        btnPresencialPostulante.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnPresencialPostulante.setText("Presencial");
        btnPresencialPostulante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPresencialPostulanteActionPerformed(evt);
            }
        });

        btnSiguientePostulante.setText("Siguiente");
        btnSiguientePostulante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguientePostulanteActionPerformed(evt);
            }
        });

        btnCancelarPostulante.setText("Cancelar");
        btnCancelarPostulante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPostulanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDireccionPostulante)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDireccionPostulante, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCedulaPostulante)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCedulaPostulante, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTelefonoPostulante)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                                .addComponent(txtTelefonoPostulante, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblMailPostulante)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtMailPostulante, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblLinkedinPostulante)
                                            .addComponent(lblFormato))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtLinkedinPostulante, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(btnRemotoPostulante)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnPresencialPostulante)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnMixtoPostulante))))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNombrePostulante)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(txtNombrePostulante, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnCancelarPostulante, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSiguientePostulante, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombrePostulante)
                    .addComponent(txtNombrePostulante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedulaPostulante)
                    .addComponent(txtCedulaPostulante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccionPostulante)
                    .addComponent(txtDireccionPostulante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefonoPostulante)
                    .addComponent(txtTelefonoPostulante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMailPostulante)
                    .addComponent(txtMailPostulante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLinkedinPostulante, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtLinkedinPostulante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFormato)
                    .addComponent(btnRemotoPostulante)
                    .addComponent(btnMixtoPostulante)
                    .addComponent(btnPresencialPostulante))
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarPostulante, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSiguientePostulante, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(6, 6, 561, 429);

        setBounds(0, 0, 594, 474);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCedulaPostulanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaPostulanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaPostulanteActionPerformed

    private void txtNombrePostulanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrePostulanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrePostulanteActionPerformed

    private void txtMailPostulanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMailPostulanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMailPostulanteActionPerformed

    private void txtLinkedinPostulanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLinkedinPostulanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLinkedinPostulanteActionPerformed

    private void txtTelefonoPostulanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoPostulanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoPostulanteActionPerformed

    private void txtDireccionPostulanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionPostulanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionPostulanteActionPerformed

    private void btnRemotoPostulanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemotoPostulanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemotoPostulanteActionPerformed

    private void btnMixtoPostulanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMixtoPostulanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMixtoPostulanteActionPerformed

    private void btnPresencialPostulanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPresencialPostulanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPresencialPostulanteActionPerformed

    // Funcionamiento al precionar el boton siguiente 
    private void btnSiguientePostulanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguientePostulanteActionPerformed
        
        // Tomo valores ingresados
        String Nombre = txtNombrePostulante.getText();
        String CI = txtCedulaPostulante.getText();
        String Direccion = txtDireccionPostulante.getText();
        String Telefono = txtTelefonoPostulante.getText();
        String Mail = txtMailPostulante.getText();
        String Linkedin = txtLinkedinPostulante.getText();
        String Formato = "";
        
        if (btnRemotoPostulante.isSelected()) {
            Formato = "remoto";
        } 
        else if (btnMixtoPostulante.isSelected()) {
            Formato = "mixto";
        } 
        else if (btnPresencialPostulante.isSelected()){
            Formato = "presencial";
        }
       
        // Valido que ingrese datos
        if (Nombre.equals("") || CI.equals("") || Direccion.equals("") || Telefono.equals("") || Mail.equals("") || Linkedin.equals("") || Formato.equals("")){
            JOptionPane.showMessageDialog(this, "Debe llenar todos los campos.");
            
        }
        // Valido que la CI y Telefono sean numeros
        else if(!modelo.validarCiyTelNumerico(CI, Telefono)){
            JOptionPane.showMessageDialog(this, "CI o Telefono invalido.");
        }
        // Valido que la CI no este repetida
        else if (modelo.validarCedulaUnica(CI)){
            JOptionPane.showMessageDialog(this, "CI ya existente.");
        }
        else{
            // Creo el postulante con los datos ingresados y abro la ventana de siguiente alta usuario
            Postulante p = new Postulante(Nombre,CI,Direccion,Telefono,Mail,Linkedin, Formato);
            dispose();
            SiguienteVentanaAltaPostulante v = new SiguienteVentanaAltaPostulante(modelo, p);
            v.setVisible(true);
        }
            
        
    }//GEN-LAST:event_btnSiguientePostulanteActionPerformed

    private void btnCancelarPostulanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPostulanteActionPerformed
        // Cierro la ventana
        dispose();
    }//GEN-LAST:event_btnCancelarPostulanteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaPostulante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaPostulante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaPostulante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaPostulante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltaPostulante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupoFormatoPostulante;
    private javax.swing.JButton btnCancelarPostulante;
    private javax.swing.JRadioButton btnMixtoPostulante;
    private javax.swing.JRadioButton btnPresencialPostulante;
    private javax.swing.JRadioButton btnRemotoPostulante;
    private javax.swing.JButton btnSiguientePostulante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCedulaPostulante;
    private javax.swing.JLabel lblDireccionPostulante;
    private javax.swing.JLabel lblFormato;
    private javax.swing.JLabel lblLinkedinPostulante;
    private javax.swing.JLabel lblMailPostulante;
    private javax.swing.JLabel lblNombrePostulante;
    private javax.swing.JLabel lblTelefonoPostulante;
    private javax.swing.JTextField txtCedulaPostulante;
    private javax.swing.JTextField txtDireccionPostulante;
    private javax.swing.JTextField txtLinkedinPostulante;
    private javax.swing.JTextField txtMailPostulante;
    private javax.swing.JTextField txtNombrePostulante;
    private javax.swing.JTextField txtTelefonoPostulante;
    // End of variables declaration//GEN-END:variables
}
