//Salvador Depons(303738) y Valentina Velazquez(305278)
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;
import Dominio.*;
import java.util.*;
import javax.swing.JOptionPane;

// Clase de la ventana Baja Postulante
public class BajaPostulante extends javax.swing.JFrame implements Observer {
    private Sistema modelo;

    // Constructor vacio
    public BajaPostulante() {
        initComponents();
    }
    
    // Constructor 
    public BajaPostulante(Sistema unSistema) {
        modelo = unSistema;
        initComponents();
        cargarLista();
        modelo.addObserver(this);
    }
    
    // Funcion update para actualizar el JList
    @Override
    public void update(Observable o, Object arg){
        cargarLista();
    }
    
    // Funcion que toma la lista de postulantes y la carga al JList
    public void cargarLista(){
        ArrayList<Postulante> posts = modelo.getListaPostulantes();
        Postulante[] PostultantesArray = new Postulante[posts.size()];

        for (int i = 0; i < posts.size(); i++) {
            PostultantesArray[i] = posts.get(i);
        }

        lstListaDePostulantes.setListData(PostultantesArray);
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblBajaPostulantes = new javax.swing.JLabel();
        PnlScrollListaPostulantes = new javax.swing.JScrollPane();
        lstListaDePostulantes = new javax.swing.JList<>();
        lblPostulanteBaja = new javax.swing.JLabel();
        btnCancelarBajaPostulantes = new javax.swing.JButton();
        btnEliminarBajaPostulantes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Baja de postulante");
        getContentPane().setLayout(null);

        lblBajaPostulantes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblBajaPostulantes.setText("Baja de Postulante");

        lstListaDePostulantes.setToolTipText("");
        PnlScrollListaPostulantes.setViewportView(lstListaDePostulantes);

        lblPostulanteBaja.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblPostulanteBaja.setText("Postulante:");

        btnCancelarBajaPostulantes.setText("Cancelar");
        btnCancelarBajaPostulantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarBajaPostulantesActionPerformed(evt);
            }
        });

        btnEliminarBajaPostulantes.setText("Eliminar");
        btnEliminarBajaPostulantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarBajaPostulantesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelarBajaPostulantes, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblPostulanteBaja)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblBajaPostulantes, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PnlScrollListaPostulantes, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarBajaPostulantes, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(lblBajaPostulantes)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PnlScrollListaPostulantes, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPostulanteBaja))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarBajaPostulantes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarBajaPostulantes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 454, 440);

        setBounds(0, 0, 476, 460);
    }// </editor-fold>//GEN-END:initComponents

    // Funcionamiento del boton de eliminar postulante
    private void btnEliminarBajaPostulantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarBajaPostulantesActionPerformed

        try{
            // Valido que este seleccionado algo 
            if(lstListaDePostulantes.getSelectedValue() != null){
                // Tomo el postulante y lo elimino junto a sus entrevistas
                Postulante p = lstListaDePostulantes.getSelectedValue();
                ArrayList<Entrevista> entrevistasP = modelo.entrevistasDePostulante(p);
                for (Entrevista e: entrevistasP){
                    modelo.quitarEntrevista(e);   
                }
                modelo.quitarPostulante(p);
                cargarLista();   
            }else{
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ningún elemento para eliminar.");
            }
        // Capturo Exeption 
        }catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnEliminarBajaPostulantesActionPerformed

    private void btnCancelarBajaPostulantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarBajaPostulantesActionPerformed
        // Cierro Ventanta
        dispose();
    }//GEN-LAST:event_btnCancelarBajaPostulantesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BajaPostulante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BajaPostulante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BajaPostulante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BajaPostulante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BajaPostulante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane PnlScrollListaPostulantes;
    private javax.swing.JButton btnCancelarBajaPostulantes;
    private javax.swing.JButton btnEliminarBajaPostulantes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBajaPostulantes;
    private javax.swing.JLabel lblPostulanteBaja;
    private javax.swing.JList<Postulante> lstListaDePostulantes;
    // End of variables declaration//GEN-END:variables
}
