//Salvador Depons(303738) y Valentina Velazquez(305278)
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;
import Dominio.*;
import java.util.*;

// Clase de la ventana Consulta Por Tematica
public class ConsultaPorTematica extends javax.swing.JFrame implements Observer {
    Sistema modelo;
  
    // Constructor vacio
    public ConsultaPorTematica() {
        initComponents();
    }
    
    // Constructor 
    public ConsultaPorTematica(Sistema elSistema) {
        modelo = elSistema;
        initComponents();
        cargarLista();
        modelo.addObserver(this);
    }
    
    // Metodo update que mantiene actualizada la lista de tematicas y los resultados de la consulta
    @Override
    public void update(Observable o, Object arg){
        Tematica Tem = listTematicasConsultaPorTematica.getSelectedValue();
        cargarLista();
        listTematicasConsultaPorTematica.setSelectedValue(Tem, true);
        lblNumeroCantPostulantesConsultaPorTematica.setText(modelo.postulantes5Mayor(Tem));
        lblNumeroCantPuestosConsultaPorTematica.setText(modelo.cantPuestosInteresadosEnTem(Tem));
        System.out.println(modelo.cantPuestosInteresadosEnTem(Tem));
    }
    
    // Metodo que se encarga de cargar la lista de tematicas
    public void cargarLista(){
        ArrayList<Tematica> lasTematicas = modelo.getListaTematicas();
        Tematica[] lasTematicasArray = new Tematica[lasTematicas.size()];
        for(int i=0 ; i<lasTematicas.size(); i++){
            lasTematicasArray[i] = lasTematicas.get(i);
        }
        listTematicasConsultaPorTematica.setListData(lasTematicasArray);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblConsultaPorTematica = new javax.swing.JLabel();
        lblTematicasConsultaPorTematica = new javax.swing.JLabel();
        ListTematicasConsultaPorTematica = new javax.swing.JScrollPane();
        listTematicasConsultaPorTematica = new javax.swing.JList<>();
        lblPostulantes5oMayorConsultaPorTematica = new javax.swing.JLabel();
        lblNumeroCantPostulantesConsultaPorTematica = new javax.swing.JLabel();
        lblPostulantes5oMayorConsultaPorTematica1 = new javax.swing.JLabel();
        lblNumeroCantPuestosConsultaPorTematica = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta por Tematica");
        getContentPane().setLayout(null);

        lblConsultaPorTematica.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblConsultaPorTematica.setText("Consulta por Temática");
        getContentPane().add(lblConsultaPorTematica);
        lblConsultaPorTematica.setBounds(200, 20, 210, 20);

        lblTematicasConsultaPorTematica.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTematicasConsultaPorTematica.setText("Temáticas:");
        getContentPane().add(lblTematicasConsultaPorTematica);
        lblTematicasConsultaPorTematica.setBounds(40, 60, 110, 16);

        listTematicasConsultaPorTematica.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listTematicasConsultaPorTematicaValueChanged(evt);
            }
        });
        ListTematicasConsultaPorTematica.setViewportView(listTematicasConsultaPorTematica);

        getContentPane().add(ListTematicasConsultaPorTematica);
        ListTematicasConsultaPorTematica.setBounds(40, 80, 490, 130);

        lblPostulantes5oMayorConsultaPorTematica.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPostulantes5oMayorConsultaPorTematica.setText("Cantidad de puestos que buscan que requieran conocimiento en esta temática:");
        getContentPane().add(lblPostulantes5oMayorConsultaPorTematica);
        lblPostulantes5oMayorConsultaPorTematica.setBounds(40, 270, 440, 16);

        lblNumeroCantPostulantesConsultaPorTematica.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumeroCantPostulantesConsultaPorTematica.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblNumeroCantPostulantesConsultaPorTematica);
        lblNumeroCantPostulantesConsultaPorTematica.setBounds(290, 240, 50, 20);

        lblPostulantes5oMayorConsultaPorTematica1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPostulantes5oMayorConsultaPorTematica1.setText("Cantidad de postulantes con nivel 5 o mayor:");
        getContentPane().add(lblPostulantes5oMayorConsultaPorTematica1);
        lblPostulantes5oMayorConsultaPorTematica1.setBounds(40, 240, 260, 16);
        getContentPane().add(lblNumeroCantPuestosConsultaPorTematica);
        lblNumeroCantPuestosConsultaPorTematica.setBounds(480, 270, 50, 20);

        setBounds(0, 0, 605, 377);
    }// </editor-fold>//GEN-END:initComponents
    
    // Funcionamiento al seleccionar un elemento de la lista
    private void listTematicasConsultaPorTematicaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listTematicasConsultaPorTematicaValueChanged
        // Tomo la tematica seleccionada y llamo a las funciones que chequean la consulta
        Tematica tem = listTematicasConsultaPorTematica.getSelectedValue();
        lblNumeroCantPostulantesConsultaPorTematica.setText(modelo.postulantes5Mayor(tem));
        lblNumeroCantPuestosConsultaPorTematica.setText(modelo.cantPuestosInteresadosEnTem(tem)); 
    }//GEN-LAST:event_listTematicasConsultaPorTematicaValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaPorTematica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaPorTematica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaPorTematica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaPorTematica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaPorTematica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ListTematicasConsultaPorTematica;
    private javax.swing.JLabel lblConsultaPorTematica;
    private javax.swing.JLabel lblNumeroCantPostulantesConsultaPorTematica;
    private javax.swing.JLabel lblNumeroCantPuestosConsultaPorTematica;
    private javax.swing.JLabel lblPostulantes5oMayorConsultaPorTematica;
    private javax.swing.JLabel lblPostulantes5oMayorConsultaPorTematica1;
    private javax.swing.JLabel lblTematicasConsultaPorTematica;
    private javax.swing.JList<Tematica> listTematicasConsultaPorTematica;
    // End of variables declaration//GEN-END:variables
}
