//Salvador Depons(303738) y Valentina Velazquez(305278)

package Interfaz;
import Dominio.*;
import java.util.*;
import javax.swing.JOptionPane;

// Clase de la ventana Ingreso Entrevista
public class IngresoEntrevista extends javax.swing.JFrame implements Observer{
    
    private Sistema modelo;
  
    // Constructor vacio
    public IngresoEntrevista() {
        initComponents();
    }
    
    // Constructor 
    public IngresoEntrevista(Sistema unSistema) {
        modelo = unSistema;
        initComponents();
        cargarListaEvauadores();
        cargarListaPostulantes();
        modelo.addObserver(this);
    }
    
    // Metodo update que mantiene actualizada la lista de evaluadores y postulantes
    @Override
    public void update(Observable o, Object arg){
        cargarListaEvauadores();
        cargarListaPostulantes();
    }
    
    // Metodo que carga la lista de evaluadores
    public void cargarListaEvauadores(){
        ArrayList<Evaluador> evaluadores = modelo.getListaEvaluadores();
        Evaluador[] EvaluadoresArray = new Evaluador[evaluadores.size()];

        for(int i = 0; i < evaluadores.size(); i++){
            Evaluador eva = evaluadores.get(i);
            EvaluadoresArray[i] = eva;
        }
        
        listEvaluadoresIngresoEntrevista.setListData(EvaluadoresArray);
    }
    
    // Metodo que carga la lista de postulantes
    public void cargarListaPostulantes(){
        ArrayList<Postulante> postulantes = modelo.getListaPostulantes();
        Postulante[] PostulantesArray = new Postulante[postulantes.size()];

        for(int i = 0; i < postulantes.size(); i++){
            Postulante pos = postulantes.get(i);
            PostulantesArray[i] = pos;
        }

        listPostulantesIngresoEntrevista.setListData(PostulantesArray);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblIngresoEntrevista = new javax.swing.JLabel();
        lblEvaluadoresIngresoEntrevista = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPostulantesIngresoEntrevista = new javax.swing.JList<>();
        lblPostulanesIngresoEntrevista = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listEvaluadoresIngresoEntrevista = new javax.swing.JList<>();
        lblComentarioIngresoEntrevista = new javax.swing.JLabel();
        textComentarioIngresoEntrevista = new javax.swing.JScrollPane();
        listComentarioIngresoEntrevista = new javax.swing.JTextArea();
        lblPuntajeIngresoEntrevista = new javax.swing.JLabel();
        comboPuntajeIngresoEntrevista = new javax.swing.JComboBox<>();
        btnRegistrarIngresoEntrevista = new javax.swing.JButton();
        btnCancelarIngresoEntrevista = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ingreso Entrevista");
        getContentPane().setLayout(null);

        lblIngresoEntrevista.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIngresoEntrevista.setText("Ingreso Entrevista");

        lblEvaluadoresIngresoEntrevista.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEvaluadoresIngresoEntrevista.setText("Evaluadores:");

        jScrollPane1.setViewportView(listPostulantesIngresoEntrevista);

        lblPostulanesIngresoEntrevista.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPostulanesIngresoEntrevista.setText("Postulantes:");

        jScrollPane2.setViewportView(listEvaluadoresIngresoEntrevista);

        lblComentarioIngresoEntrevista.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblComentarioIngresoEntrevista.setText("Comentarios de la entrevista:");

        listComentarioIngresoEntrevista.setColumns(20);
        listComentarioIngresoEntrevista.setRows(5);
        textComentarioIngresoEntrevista.setViewportView(listComentarioIngresoEntrevista);

        lblPuntajeIngresoEntrevista.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPuntajeIngresoEntrevista.setText("Puntaje:");

        comboPuntajeIngresoEntrevista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100" }));
        comboPuntajeIngresoEntrevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPuntajeIngresoEntrevistaActionPerformed(evt);
            }
        });

        btnRegistrarIngresoEntrevista.setText("Registrar");
        btnRegistrarIngresoEntrevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarIngresoEntrevistaActionPerformed(evt);
            }
        });

        btnCancelarIngresoEntrevista.setText("Cancelar");
        btnCancelarIngresoEntrevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarIngresoEntrevistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(textComentarioIngresoEntrevista, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(211, 211, 211)
                                    .addComponent(lblIngresoEntrevista))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblEvaluadoresIngresoEntrevista)
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblPostulanesIngresoEntrevista)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lblPuntajeIngresoEntrevista, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(comboPuntajeIngresoEntrevista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancelarIngresoEntrevista)
                            .addGap(36, 36, 36)
                            .addComponent(btnRegistrarIngresoEntrevista)))
                    .addComponent(lblComentarioIngresoEntrevista))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIngresoEntrevista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEvaluadoresIngresoEntrevista)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPostulanesIngresoEntrevista)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblComentarioIngresoEntrevista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textComentarioIngresoEntrevista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboPuntajeIngresoEntrevista, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrarIngresoEntrevista)
                    .addComponent(btnCancelarIngresoEntrevista)
                    .addComponent(lblPuntajeIngresoEntrevista))
                .addGap(39, 39, 39))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 10, 590, 450);

        setBounds(0, 0, 632, 483);
    }// </editor-fold>//GEN-END:initComponents

    private void comboPuntajeIngresoEntrevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPuntajeIngresoEntrevistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboPuntajeIngresoEntrevistaActionPerformed

    private void btnCancelarIngresoEntrevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarIngresoEntrevistaActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarIngresoEntrevistaActionPerformed
    
    //Funncionamiento del boton resgistrar
    private void btnRegistrarIngresoEntrevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarIngresoEntrevistaActionPerformed
        
        // Toma los datos seleccioandos
        Postulante p = listPostulantesIngresoEntrevista.getSelectedValue();
        Evaluador e = listEvaluadoresIngresoEntrevista.getSelectedValue();
        String com = listComentarioIngresoEntrevista.getText();
        String puntaje = (String)comboPuntajeIngresoEntrevista.getSelectedItem();
        String numero = "";
        
        // Verifica que esten ambas listas seleccionadas
        if (listEvaluadoresIngresoEntrevista.isSelectionEmpty() || listPostulantesIngresoEntrevista.isSelectionEmpty()){
            JOptionPane.showMessageDialog(this, "Debe Seleccionar Postulante y Evaluador.");
          // Verifica que llene todos los datos
        } else if (listComentarioIngresoEntrevista.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debe completar todos los campos.");
        } else{
            // Creo una nueva entrevista con los datos y la agrego a la lista, ademas incremento el contador de entervistas
            modelo.aumentarCantDeEntrevistas();
            numero = Integer.toString(modelo.getCantEntrevistas());
            Entrevista entre = new Entrevista(e, p, com, puntaje, numero);
            JOptionPane.showMessageDialog(this, "Su numero de entrevista es: " + numero + ".");
            modelo.agregarEntrevista(entre);
            listComentarioIngresoEntrevista.setText("");
            comboPuntajeIngresoEntrevista.setSelectedIndex(0);
            listEvaluadoresIngresoEntrevista.clearSelection();
            listPostulantesIngresoEntrevista.clearSelection();//hay que hacer que no se cierre? preguntarle a la profe igual
        }

    }//GEN-LAST:event_btnRegistrarIngresoEntrevistaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresoEntrevista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresoEntrevista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresoEntrevista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresoEntrevista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresoEntrevista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarIngresoEntrevista;
    private javax.swing.JButton btnRegistrarIngresoEntrevista;
    private javax.swing.JComboBox<String> comboPuntajeIngresoEntrevista;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblComentarioIngresoEntrevista;
    private javax.swing.JLabel lblEvaluadoresIngresoEntrevista;
    private javax.swing.JLabel lblIngresoEntrevista;
    private javax.swing.JLabel lblPostulanesIngresoEntrevista;
    private javax.swing.JLabel lblPuntajeIngresoEntrevista;
    private javax.swing.JTextArea listComentarioIngresoEntrevista;
    private javax.swing.JList<Evaluador> listEvaluadoresIngresoEntrevista;
    private javax.swing.JList<Postulante> listPostulantesIngresoEntrevista;
    private javax.swing.JScrollPane textComentarioIngresoEntrevista;
    // End of variables declaration//GEN-END:variables
}
