//Salvador Depons(303738) y Valentina Velazquez(305278)

package Interfaz;

import Dominio.Sistema;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.nio.file.Files;
import java.nio.file.Paths;

// Clase de la ventana Inicio
public class Inicio extends javax.swing.JFrame {

    private Sistema modelo;
    
    // Constructor vacio
    public Inicio() {
        initComponents();
    }
    
    // Constructor 
    public Inicio(Sistema elSistema){
        modelo = elSistema;
        initComponents();
    }

    // Metodo encargado de recuperar el sistema previo
    public static Sistema cargarSistema(){
        Sistema resultado = null;
        try{
            // Le digo que intente cargar los datos del archivo "Sistema.ser" y creo un nuevo sistema con los datos
            ObjectInputStream in = new ObjectInputStream(Files.newInputStream(Paths.get("Sistema.ser")));
            Sistema nuevoSis = (Sistema) in.readObject();
            resultado = nuevoSis;
            in.close();
        // Capturo Exeption
        }catch(IOException | ClassNotFoundException e){
            System.out.println("Error al cargar");
        }
        return resultado;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblRestaurarSistema = new javax.swing.JLabel();
        btnSiRestaurar = new javax.swing.JButton();
        btnNoRestaurar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio");
        getContentPane().setLayout(null);

        lblRestaurarSistema.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblRestaurarSistema.setText("¿Desea restaurar el sistema previo?");

        btnSiRestaurar.setText("Si");
        btnSiRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiRestaurarActionPerformed(evt);
            }
        });

        btnNoRestaurar.setText("No");
        btnNoRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoRestaurarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSiRestaurar)
                        .addGap(132, 132, 132)
                        .addComponent(btnNoRestaurar))
                    .addComponent(lblRestaurarSistema))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblRestaurarSistema)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSiRestaurar)
                    .addComponent(btnNoRestaurar))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 336, 148);

        setBounds(0, 0, 364, 160);
    }// </editor-fold>//GEN-END:initComponents

    // Funcionamiento del boton Si
    private void btnSiRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiRestaurarActionPerformed
        // Valido si el sistema tiene datos, creo la ventana con los datos y la muestro
        if (cargarSistema().equals(new Sistema())){
            MenuVentanas m = new MenuVentanas(modelo);
            dispose();
            m.setVisible(true);
        }else{
            MenuVentanas m = new MenuVentanas(cargarSistema());
            dispose();
            m.setVisible(true);    
        } 
    }//GEN-LAST:event_btnSiRestaurarActionPerformed
    
    //Funcionamiento del boton No
    private void btnNoRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoRestaurarActionPerformed
        // Creo una ventana menu con un sistema nuevo
        MenuVentanas m = new MenuVentanas(modelo);
        dispose();
        m.setVisible(true);
    }//GEN-LAST:event_btnNoRestaurarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNoRestaurar;
    private javax.swing.JButton btnSiRestaurar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblRestaurarSistema;
    // End of variables declaration//GEN-END:variables
}
