//Salvador Depons(303738) y Valentina Velazquez(305278)

package Interfaz;

import Dominio.*;
import javax.swing.JOptionPane;

// Clase de la ventana Registro Evaluador
public class RegistroEvaluador extends javax.swing.JFrame {
    private Sistema modelo;

    // Constructor vacio
    public RegistroEvaluador() {
        initComponents();
        modelo = new Sistema();
    }
    
    // Constructor 
    public RegistroEvaluador(Sistema unSistema){
        modelo = unSistema;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblRegistroEvaluador = new javax.swing.JLabel();
        lblDirecRegistroEvaluador = new javax.swing.JLabel();
        lblNombreRegistroEvaluador = new javax.swing.JLabel();
        lblCIRegistroEvaluador = new javax.swing.JLabel();
        lblAnoIngresoRegistroEvaluador = new javax.swing.JLabel();
        txtNombreRegistroEvaluador = new javax.swing.JTextField();
        txtDirecRegistroEvaluador = new javax.swing.JTextField();
        txtCIRegistroEvaluador = new javax.swing.JTextField();
        ComboAnoIngresoRegistroEvaluador = new javax.swing.JComboBox<>();
        btnRegistrarRegistroEvaluador = new javax.swing.JButton();
        btnCancelarRegistroEvaluador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de Evaluador");
        getContentPane().setLayout(null);

        lblRegistroEvaluador.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRegistroEvaluador.setText("Registro de evaluador");

        lblDirecRegistroEvaluador.setText("Direccion:");

        lblNombreRegistroEvaluador.setText("Nombre:");

        lblCIRegistroEvaluador.setText("Cédula:");

        lblAnoIngresoRegistroEvaluador.setText("Año de ingreso:");

        ComboAnoIngresoRegistroEvaluador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1800", "1801", "1802", "1803", "1804", "1805", "1806", "1807", "1808", "1809", "1810", "1811", "1812", "1813", "1814", "1815", "1816", "1817", "1818", "1819", "1820", "1821", "1822", "1823", "1824", "1825", "1826", "1827", "1828", "1829", "1830", "1831", "1832", "1833", "1834", "1835", "1836", "1837", "1838", "1839", "1840", "1841", "1842", "1843", "1844", "1845", "1846", "1847", "1848", "1849", "1850", "1851", "1852", "1853", "1854", "1855", "1856", "1857", "1858", "1859", "1860", "1861", "1862", "1863", "1864", "1865", "1866", "1867", "1868", "1869", "1870", "1871", "1872", "1873", "1874", "1875", "1876", "1877", "1878", "1879", "1880", "1881", "1882", "1883", "1884", "1885", "1886", "1887", "1888", "1889", "1890", "1891", "1892", "1893", "1894", "1895", "1896", "1897", "1898", "1899", "1900", "1901", "1902", "1903", "1904", "1905", "1906", "1907", "1908", "1909", "1910", "1911", "1912", "1913", "1914", "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023" }));

        btnRegistrarRegistroEvaluador.setText("Registrar");
        btnRegistrarRegistroEvaluador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarRegistroEvaluadorActionPerformed(evt);
            }
        });

        btnCancelarRegistroEvaluador.setText("Cancelar");
        btnCancelarRegistroEvaluador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarRegistroEvaluadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDirecRegistroEvaluador)
                    .addComponent(lblCIRegistroEvaluador)
                    .addComponent(lblNombreRegistroEvaluador)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblAnoIngresoRegistroEvaluador)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ComboAnoIngresoRegistroEvaluador, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCancelarRegistroEvaluador, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRegistrarRegistroEvaluador, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreRegistroEvaluador, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegistroEvaluador)
                    .addComponent(txtCIRegistroEvaluador, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDirecRegistroEvaluador, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblRegistroEvaluador)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreRegistroEvaluador)
                    .addComponent(txtNombreRegistroEvaluador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCIRegistroEvaluador)
                    .addComponent(txtCIRegistroEvaluador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDirecRegistroEvaluador)
                    .addComponent(txtDirecRegistroEvaluador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnoIngresoRegistroEvaluador)
                    .addComponent(ComboAnoIngresoRegistroEvaluador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarRegistroEvaluador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrarRegistroEvaluador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 500, 320);

        setBounds(0, 0, 536, 356);
    }// </editor-fold>//GEN-END:initComponents

    //Funcionamiento del boton registrar
    private void btnRegistrarRegistroEvaluadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarRegistroEvaluadorActionPerformed
        //Tomo los datos ingresados
        String Nombre = txtNombreRegistroEvaluador.getText();
        String CI = txtCIRegistroEvaluador.getText();
        String Direc = txtDirecRegistroEvaluador.getText();
        String AnoIngreso = (String)ComboAnoIngresoRegistroEvaluador.getSelectedItem();
        // Valido que esten todos los campos llenados
        if(Nombre.equals("") || CI.equals("") || Direc.equals("") || AnoIngreso.equals("")){
            JOptionPane.showMessageDialog(this, "Debe completar todos los campos");
        }
        // Valido CI unica
        else if(modelo.validarCedulaUnica(CI)){
            JOptionPane.showMessageDialog(this, "CI ya existente.");
        // Valido que la CI sea un número
        }else if(!modelo.validarCiyTelNumerico(CI, "0")){
            JOptionPane.showMessageDialog(this, "CI invalido.");
        }else{
            // Creo un evaluador con los datos y lo agrego a la lista
            Evaluador e = new Evaluador(Nombre, CI, Direc, AnoIngreso);
            modelo.agregarEvaluador(e);
            modelo.agregarPersona(e);
            txtNombreRegistroEvaluador.setText("");
            txtCIRegistroEvaluador.setText("");
            txtDirecRegistroEvaluador.setText("");
            ComboAnoIngresoRegistroEvaluador.setSelectedIndex(0);
            }
        
    }//GEN-LAST:event_btnRegistrarRegistroEvaluadorActionPerformed

    private void btnCancelarRegistroEvaluadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarRegistroEvaluadorActionPerformed
        // Cierro la ventana
        dispose();
    }//GEN-LAST:event_btnCancelarRegistroEvaluadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroEvaluador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroEvaluador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroEvaluador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroEvaluador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroEvaluador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboAnoIngresoRegistroEvaluador;
    private javax.swing.JButton btnCancelarRegistroEvaluador;
    private javax.swing.JButton btnRegistrarRegistroEvaluador;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAnoIngresoRegistroEvaluador;
    private javax.swing.JLabel lblCIRegistroEvaluador;
    private javax.swing.JLabel lblDirecRegistroEvaluador;
    private javax.swing.JLabel lblNombreRegistroEvaluador;
    private javax.swing.JLabel lblRegistroEvaluador;
    private javax.swing.JTextField txtCIRegistroEvaluador;
    private javax.swing.JTextField txtDirecRegistroEvaluador;
    private javax.swing.JTextField txtNombreRegistroEvaluador;
    // End of variables declaration//GEN-END:variables
}
