//Salvador Depons(303738) y Valentina Velazquez(305278)
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Dominio.*;
import java.util.ArrayList;
import java.util.*;
import javax.swing.JOptionPane;

// Clase de la ventana Registro Puesto
public class RegistroPuesto extends javax.swing.JFrame implements Observer{

    private Sistema modelo;
    private ArrayList<Tematica> temas;
    
    // Constructor vacio
    public RegistroPuesto() {
        initComponents();
    }
    
    // Constructor 
    public RegistroPuesto(Sistema unSistema){
        modelo = unSistema;
        temas = new ArrayList<>();
        initComponents();
        cargarLista();
        cargarListaElegidas();
        modelo.addObserver(this);
    }
    
    // Metodo update que mantiene la lista actualizada
    @Override
    public void update(Observable o, Object arg){
        cargarLista();
    }
    
    // Metodo para cargar la lista de tematicas elegidas
    public void cargarListaElegidas(){
        ArrayList<Tematica> Tematicas = this.temas;
        Tematica[] tematicasArray = new Tematica[Tematicas.size()];

        for (int i = 0; i < Tematicas.size(); i++) {
             Tematica tem = Tematicas.get(i);
             tematicasArray[i] = tem;
        }

        ListaTematicasElegidas.setListData(tematicasArray);        
    }
    
    // Metodo para cargar la lista de las tematicas 
    public void cargarLista(){
        ArrayList<Tematica> tematicas = modelo.getListaTematicas();
        Tematica[] TematicasArray = new Tematica[tematicas.size()];

        for(int i = 0; i < tematicas.size(); i++){
            Tematica tem = tematicas.get(i);
            TematicasArray[i] = tem;
        }

        listListaTemasRequeridosPuesto.setListData(TematicasArray);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTipoPuesto = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblRegistroDePuesto = new javax.swing.JLabel();
        lblNombreRegistroPuesto = new javax.swing.JLabel();
        lblTipoPuesto = new javax.swing.JLabel();
        lblTemasRequeridos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listListaTemasRequeridosPuesto = new javax.swing.JList<>();
        rbtnPresencialPuesto = new javax.swing.JRadioButton();
        rbtnRemotoPuesto = new javax.swing.JRadioButton();
        rbtnMixtoPuesto = new javax.swing.JRadioButton();
        btnAgregarTemaPuesto = new javax.swing.JButton();
        btnEliminarTemaPuesto = new javax.swing.JButton();
        lblTematicasElegidas = new javax.swing.JLabel();
        btnCancelarPuesto = new javax.swing.JButton();
        btnRegistrarPuesto = new javax.swing.JButton();
        txtNombrePuestoRegistro = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaTematicasElegidas = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de Puesto");
        getContentPane().setLayout(null);

        lblRegistroDePuesto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRegistroDePuesto.setText("Registro de puesto");

        lblNombreRegistroPuesto.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblNombreRegistroPuesto.setText("Nombre: ");

        lblTipoPuesto.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblTipoPuesto.setText("Tipo:");

        lblTemasRequeridos.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblTemasRequeridos.setText("Agregar Temática:");

        jScrollPane1.setViewportView(listListaTemasRequeridosPuesto);

        grupoTipoPuesto.add(rbtnPresencialPuesto);
        rbtnPresencialPuesto.setText("Presencial");
        rbtnPresencialPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnPresencialPuestoActionPerformed(evt);
            }
        });

        grupoTipoPuesto.add(rbtnRemotoPuesto);
        rbtnRemotoPuesto.setSelected(true);
        rbtnRemotoPuesto.setText("Remoto");
        rbtnRemotoPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnRemotoPuestoActionPerformed(evt);
            }
        });

        grupoTipoPuesto.add(rbtnMixtoPuesto);
        rbtnMixtoPuesto.setText("Mixto");
        rbtnMixtoPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMixtoPuestoActionPerformed(evt);
            }
        });

        btnAgregarTemaPuesto.setText("Agregar temática");
        btnAgregarTemaPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarTemaPuestoActionPerformed(evt);
            }
        });

        btnEliminarTemaPuesto.setText("Eliminar temática");
        btnEliminarTemaPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTemaPuestoActionPerformed(evt);
            }
        });

        lblTematicasElegidas.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblTematicasElegidas.setText("Tematicas elegidas:");

        btnCancelarPuesto.setText("Cancelar");
        btnCancelarPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPuestoActionPerformed(evt);
            }
        });

        btnRegistrarPuesto.setText("Registrar");
        btnRegistrarPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPuestoActionPerformed(evt);
            }
        });

        txtNombrePuestoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombrePuestoRegistroActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(ListaTematicasElegidas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCancelarPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTematicasElegidas)
                            .addComponent(btnEliminarTemaPuesto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblRegistroDePuesto)
                                        .addGap(0, 180, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnRegistrarPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
                            .addComponent(jScrollPane2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNombreRegistroPuesto)
                            .addComponent(lblTipoPuesto)
                            .addComponent(lblTemasRequeridos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAgregarTemaPuesto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbtnRemotoPuesto)
                                .addGap(72, 72, 72)
                                .addComponent(rbtnPresencialPuesto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbtnMixtoPuesto))
                            .addComponent(txtNombrePuestoRegistro)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jScrollPane1))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRegistroDePuesto)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreRegistroPuesto)
                    .addComponent(txtNombrePuestoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoPuesto)
                    .addComponent(rbtnRemotoPuesto)
                    .addComponent(rbtnMixtoPuesto)
                    .addComponent(rbtnPresencialPuesto))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTemasRequeridos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAgregarTemaPuesto))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTematicasElegidas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminarTemaPuesto)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegistrarPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelarPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 500, 400);

        setBounds(0, 0, 536, 429);
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void rbtnRemotoPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnRemotoPuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnRemotoPuestoActionPerformed

    private void rbtnMixtoPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMixtoPuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnMixtoPuestoActionPerformed

    private void rbtnPresencialPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnPresencialPuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnPresencialPuestoActionPerformed

    // Funcionamiento del boton agregar tematica
    private void btnAgregarTemaPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarTemaPuestoActionPerformed
        
        // Tomo la tematica seleccionada
        Tematica temax = listListaTemasRequeridosPuesto.getSelectedValue();
        
        // Verifico que el tema no este seleccionado y cargo la lista con el nuevo tema 
        if (temas.contains(temax)){
           JOptionPane.showMessageDialog(this, "Tema ya elegido.");
        }else if(listListaTemasRequeridosPuesto.isSelectionEmpty()){
           JOptionPane.showMessageDialog(this, "No hay ninguna tematica seleccionada.");
        }else{
           temas.add(temax);
           cargarListaElegidas();
        }      
        
     
    }//GEN-LAST:event_btnAgregarTemaPuestoActionPerformed

    // Funcionamiento del boton eliminar tematica
    private void btnEliminarTemaPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTemaPuestoActionPerformed
        
        // Tomo la tematica seleccioanda
        Tematica temax = ListaTematicasElegidas.getSelectedValue();
        try{
            // Si esta en la lista el seleccionado lo elimino 
            if (temas.contains(temax)){
                temas.remove(temax);
                cargarListaElegidas();  
            // Verifico que la lista tenga elementos 
            }else if(temas.size() == 0){
                JOptionPane.showMessageDialog(this, "No existen temas agregados."); 
            }else{
                JOptionPane.showMessageDialog(this, "El tema seleccionado no esta agregado."); 
            }
        // Capturo Expetion
        }catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnEliminarTemaPuestoActionPerformed

    private void btnCancelarPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPuestoActionPerformed
        // Cierro ventana
        dispose();
    }//GEN-LAST:event_btnCancelarPuestoActionPerformed

    // Funcionamiento del boton registro
    private void btnRegistrarPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPuestoActionPerformed

        // Tomo los datos ingresados
        String nom = txtNombrePuestoRegistro.getText();
        String Formato = "";
        if (rbtnRemotoPuesto.isSelected()) {
            Formato = "remoto";
        } else if (rbtnMixtoPuesto.isSelected()) {
            Formato = "mixto";
        } else if (rbtnPresencialPuesto.isSelected()) {
            Formato = "presencial";
        }
        // Verifico que los campos tengan datos
        if(nom.equals("") || Formato.equals("")){
            JOptionPane.showMessageDialog(this, "Debe llenar todos los campos.");
        // Verifico que tenga tematicas ingresada
        }else if(temas.size() == 0){
            JOptionPane.showMessageDialog(this, "Debe agregar al menos una tematica.");
        // Verifico que el nombre puesto no exista
        }else if(modelo.verificarPuestoUnicoPorNombre(nom)){
            JOptionPane.showMessageDialog(this, "El nombre del puesto ya existe.");
        }else{
            // Creo un puesto con los datos ingresado y lo agrego a la lista
            Puesto p = new Puesto(nom, Formato, temas);
            modelo.agregarPuesto(p);
            txtNombrePuestoRegistro.setText("");
            rbtnRemotoPuesto.setSelected(true);
            temas = new ArrayList<>();
            cargarListaElegidas();
        }
    }//GEN-LAST:event_btnRegistrarPuestoActionPerformed

    private void txtNombrePuestoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrePuestoRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrePuestoRegistroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroPuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroPuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroPuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroPuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroPuesto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<Tematica> ListaTematicasElegidas;
    private javax.swing.JButton btnAgregarTemaPuesto;
    private javax.swing.JButton btnCancelarPuesto;
    private javax.swing.JButton btnEliminarTemaPuesto;
    private javax.swing.JButton btnRegistrarPuesto;
    private javax.swing.ButtonGroup grupoTipoPuesto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblNombreRegistroPuesto;
    private javax.swing.JLabel lblRegistroDePuesto;
    private javax.swing.JLabel lblTemasRequeridos;
    private javax.swing.JLabel lblTematicasElegidas;
    private javax.swing.JLabel lblTipoPuesto;
    private javax.swing.JList<Tematica> listListaTemasRequeridosPuesto;
    private javax.swing.JRadioButton rbtnMixtoPuesto;
    private javax.swing.JRadioButton rbtnPresencialPuesto;
    private javax.swing.JRadioButton rbtnRemotoPuesto;
    private javax.swing.JTextField txtNombrePuestoRegistro;
    // End of variables declaration//GEN-END:variables
}
